#!/bin/sh

# Update Ubuntu
sudo apt update && sudo apt -y upgrade
sudo apt -y autoremove && sudo apt autoclean

# Basic Ubuntu packages
sudo apt install autojump git htop vagrant virtualbox xsel zsh ack-grep

# Install NodeJS
echo "› installing NodeJS"
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt install -y nodejs

# Install Albert
echo "› installing Albert"
wget -nv -O Release.key https://build.opensuse.org/projects/home:manuelschneid3r/public_key
sudo apt-key add - < Release.key
sudo apt update

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_16.04/ /' > /etc/apt/sources.list.d/albert.list"
sudo apt update
sudo apt install albert
cp /usr/share/applications/albert.desktop ~/.config/autostart/ && chmod +x ~/.config/autostart/albert.desktop

# Install Atom
echo "› installing Atom"
wget -O atom.deb https://atom.io/download/deb
sudo dpkg -i atom.deb
rm atom.deb

# Install Slack
echo "› installing Slack"
wget -O slack.deb https://downloads.slack-edge.com/linux_releases/slack-desktop-3.0.5-amd64.deb
sudo dpkg -i slack.deb
rm slack.deb

# Install Docker
echo "› installing Docker"
sudo apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt update
sudo apt install docker-ce docker-compose
sudo groupadd docker
sudo usermod -aG docker $USER

# Install Spotify
echo "› installing Spotify"
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0DF731E45CE24F27EEEB1450EFDC8610341D9410
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt update
sudo apt install -y spotify-client
