#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Find the installers and run them iteratively
echo "› install.sh"
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
