#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# Find the installers and run them iteratively
echo "› install.sh"
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

# Installs node.js global dependencies
echo "› yarn global dependencies"
cat $DOTFILES/yarn/Yarnfile | xargs yarn global add
